version: "3"

services:
  custom_service:
    image: custom_service
    build: 
      dockerfile: Dockerfile
      context: ./custom-service
    container_name: custom-service
    restart: always
    ports:
      - 80:80
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    volumes:
        - ./grafana/etc:/etc/grafana:ro
        #- grafana-lib:/var/lib/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - monitoring
      
  influxdb:
    image: influxdb
    container_name: influxdb
    volumes:
        - ./influxdb/etc:/etc/influxdb
        #- influxdb-lib:/var/lib/influxdb
    restart: always
    ports:
      - 8086:8086
    networks:
      - monitoring
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_USER=telegraf
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=Welcome1 

  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    networks:
      - monitoring
    # extra_hosts:
    #  - "influxdb:192.168.0.110"
    volumes:
     - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
     - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  monitoring:
volumes:
  grafana-lib:
  influxdb-lib: